import { jsx as _jsx } from "react/jsx-runtime";
import * as React from 'react';
import * as TooltipPrimitive from '@radix-ui/react-tooltip';
import { cn } from '@/lib/utils';
const TooltipProvider = TooltipPrimitive.Provider;
const Tooltip = TooltipPrimitive.Root;
const TooltipTrigger = TooltipPrimitive.Trigger;
const TooltipContent = React.forwardRef(({ className, sideOffset = 8, ...props }, ref) => (_jsx(TooltipPrimitive.Content, { ref: ref, sideOffset: sideOffset, className: cn('z-50 overflow-hidden rounded-md border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium shadow-md dark:border-slate-800 dark:bg-slate-900', className), ...props })));
TooltipContent.displayName = TooltipPrimitive.Content.displayName;
export { TooltipProvider, Tooltip, TooltipTrigger, TooltipContent };
